/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LayoutRouteImport } from "./pages/_layout"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as LayoutIndexRouteImport } from "./pages/_layout/index"
import { Route as LayoutCarsCarIdRouteImport } from "./pages/_layout/cars/$carId"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCarsCarIdRoute = LayoutCarsCarIdRouteImport.update({
  id: "/cars/$carId",
  path: "/cars/$carId",
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRoute
  "/login": typeof LoginRoute
  "/cars/$carId": typeof LayoutCarsCarIdRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/": typeof LayoutIndexRoute
  "/cars/$carId": typeof LayoutCarsCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_layout": typeof LayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/cars/$carId": typeof LayoutCarsCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/login" | "/cars/$carId"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/" | "/cars/$carId"
  id: "__root__" | "/_layout" | "/login" | "/_layout/" | "/_layout/cars/$carId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/cars/$carId": {
      id: "/_layout/cars/$carId"
      path: "/cars/$carId"
      fullPath: "/cars/$carId"
      preLoaderRoute: typeof LayoutCarsCarIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCarsCarIdRoute: typeof LayoutCarsCarIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCarsCarIdRoute: LayoutCarsCarIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
