/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as LayoutRouteImport } from "./pages/_layout"
import { Route as LoginRouteImport } from "./pages/login"
import { Route as LayoutIndexRouteImport } from "./pages/_layout/index"
import { Route as LayoutCandidatesRouteImport } from "./pages/_layout/candidates"
import { Route as LayoutImportRouteImport } from "./pages/_layout/import"
import { Route as LayoutRegistryIndexRouteImport } from "./pages/_layout/registry/index"
import { Route as LayoutRegistryRouteIdRouteImport } from "./pages/_layout/registry/$routeId"

const LayoutRoute = LayoutRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCandidatesRoute = LayoutCandidatesRouteImport.update({
  id: "/candidates",
  path: "/candidates",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImportRoute = LayoutImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegistryIndexRoute = LayoutRegistryIndexRouteImport.update({
  id: "/registry/",
  path: "/registry/",
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegistryRouteIdRoute = LayoutRegistryRouteIdRouteImport.update({
  id: "/registry/$routeId",
  path: "/registry/$routeId",
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof LayoutIndexRoute
  "/login": typeof LoginRoute
  "/candidates": typeof LayoutCandidatesRoute
  "/import": typeof LayoutImportRoute
  "/registry/$routeId": typeof LayoutRegistryRouteIdRoute
  "/registry/": typeof LayoutRegistryIndexRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/candidates": typeof LayoutCandidatesRoute
  "/import": typeof LayoutImportRoute
  "/": typeof LayoutIndexRoute
  "/registry/$routeId": typeof LayoutRegistryRouteIdRoute
  "/registry": typeof LayoutRegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_layout": typeof LayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/_layout/candidates": typeof LayoutCandidatesRoute
  "/_layout/import": typeof LayoutImportRoute
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/registry/$routeId": typeof LayoutRegistryRouteIdRoute
  "/_layout/registry/": typeof LayoutRegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/candidates"
    | "/import"
    | "/registry/$routeId"
    | "/registry/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/candidates"
    | "/import"
    | "/"
    | "/registry/$routeId"
    | "/registry"
  id:
    | "__root__"
    | "/_layout"
    | "/login"
    | "/_layout/candidates"
    | "/_layout/import"
    | "/_layout/"
    | "/_layout/registry/$routeId"
    | "/_layout/registry/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/candidates": {
      id: "/_layout/candidates"
      path: "/candidates"
      fullPath: "/candidates"
      preLoaderRoute: typeof LayoutCandidatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/import": {
      id: "/_layout/import"
      path: "/import"
      fullPath: "/import"
      preLoaderRoute: typeof LayoutImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/registry/": {
      id: "/_layout/registry/"
      path: "/registry"
      fullPath: "/registry/"
      preLoaderRoute: typeof LayoutRegistryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    "/_layout/registry/$routeId": {
      id: "/_layout/registry/$routeId"
      path: "/registry/$routeId"
      fullPath: "/registry/$routeId"
      preLoaderRoute: typeof LayoutRegistryRouteIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCandidatesRoute: typeof LayoutCandidatesRoute
  LayoutImportRoute: typeof LayoutImportRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutRegistryRouteIdRoute: typeof LayoutRegistryRouteIdRoute
  LayoutRegistryIndexRoute: typeof LayoutRegistryIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCandidatesRoute: LayoutCandidatesRoute,
  LayoutImportRoute: LayoutImportRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutRegistryRouteIdRoute: LayoutRegistryRouteIdRoute,
  LayoutRegistryIndexRoute: LayoutRegistryIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
