/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/auth/login": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations["login"]
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/api/v1/auth/me": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations["me"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/api/v1/cars/stats": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description Distinct cars seen in the window, split by licence status. */
		get: operations["carsStats"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/api/v1/cars": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description Cars seen in the window, newest detection first. */
		get: operations["listCars"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/api/v1/cars/{car_id}": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations["getCar"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/api/v1/cars/{car_id}/history": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description Every detection of one car, newest first. */
		get: operations["carHistory"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		/** @enum {string} */
		LicenseStatus: "licensed" | "unlicensed"
		/** @enum {string} */
		Direction: "in" | "out"
		LoginRequest: {
			username: string
			password: string
		}
		TokenResponse: {
			access_token: string
			/** @example bearer */
			token_type: string
		}
		UserRead: {
			id: number
			username: string
			full_name: string
		}
		ErrorResponse: {
			detail: string
		}
		PageMeta: {
			total: number
			page: number
			page_size: number
		}
		CarsStats: {
			total: number
			licensed: number
			unlicensed: number
		}
		CarRead: {
			id: number
			/** @description Plate as recognised, e.g. 95A123BC */
			number: string
			status: components["schemas"]["LicenseStatus"]
			/** Format: date-time */
			first_seen_at: string
			/** Format: date-time */
			last_seen_at: string
			/** @description Detections inside the requested window */
			visits_count: number
			/** @description Photo of the latest detection */
			photo_url: string
		}
		CarsPage: {
			data: components["schemas"]["CarRead"][]
			meta: components["schemas"]["PageMeta"]
		}
		CarEventRead: {
			id: number
			/** Format: date-time */
			detected_at: string
			direction: components["schemas"]["Direction"]
			photo_url: string
		}
		CarEventsPage: {
			data: components["schemas"]["CarEventRead"][]
			meta: components["schemas"]["PageMeta"]
		}
	}
	responses: never
	parameters: {
		CarId: number
		/** @description Inclusive, YYYY-MM-DD. */
		DateFrom: string
		/** @description Inclusive, YYYY-MM-DD. */
		DateTo: string
		Page: number
		PageSize: number
	}
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	login: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"]
			}
		}
		responses: {
			/** @description Access token */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["TokenResponse"]
				}
			}
			/** @description Wrong credentials */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["ErrorResponse"]
				}
			}
		}
	}
	me: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Current user */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["UserRead"]
				}
			}
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["ErrorResponse"]
				}
			}
		}
	}
	carsStats: {
		parameters: {
			query?: {
				/** @description Inclusive, YYYY-MM-DD. */
				date_from?: components["parameters"]["DateFrom"]
				/** @description Inclusive, YYYY-MM-DD. */
				date_to?: components["parameters"]["DateTo"]
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Counters */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["CarsStats"]
				}
			}
		}
	}
	listCars: {
		parameters: {
			query?: {
				/** @description Part of the plate number, case- and space-insensitive. */
				search?: string
				status?: components["schemas"]["LicenseStatus"]
				/** @description Inclusive, YYYY-MM-DD. */
				date_from?: components["parameters"]["DateFrom"]
				/** @description Inclusive, YYYY-MM-DD. */
				date_to?: components["parameters"]["DateTo"]
				page?: components["parameters"]["Page"]
				page_size?: components["parameters"]["PageSize"]
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Page of cars */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["CarsPage"]
				}
			}
		}
	}
	getCar: {
		parameters: {
			query?: never
			header?: never
			path: {
				car_id: components["parameters"]["CarId"]
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description One car */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["CarRead"]
				}
			}
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["ErrorResponse"]
				}
			}
		}
	}
	carHistory: {
		parameters: {
			query?: {
				/** @description Inclusive, YYYY-MM-DD. */
				date_from?: components["parameters"]["DateFrom"]
				/** @description Inclusive, YYYY-MM-DD. */
				date_to?: components["parameters"]["DateTo"]
				page?: components["parameters"]["Page"]
				page_size?: components["parameters"]["PageSize"]
			}
			header?: never
			path: {
				car_id: components["parameters"]["CarId"]
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Page of detections */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["CarEventsPage"]
				}
			}
		}
	}
}
